config/routes.rb
Practic::Application.routes.draw do

  get "static_pages/about"

  get 'admin' => 'admin/index'

  resources :users

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

  resources :stations do
    resources :devices
    resources :computers
    resources :printers
    resources :modems
  end

  post "user/create"
  get "user/:id" => "User#show"

  match 'about' => 'Static_Pages#about'

 root :to => 'stations#index'

end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :name

  has_many :computers, :dependent => :destroy
  has_many :devices, :dependent => :destroy
  has_many :modems, :dependent => :destroy
  has_many :printers, :dependent => :destroy
  validates :name, :presence => :true

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
    @stations = Station.search(params[:search])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @station = Station.find(params[:id])
    @modems = @station.modems.paginate(page: params[:page])
    @printers = @station.printers.paginate(page: params[:page])
    @devices = @station.devices.paginate(page: params[:page])
    @computers = @station.computers.paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.json
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(params[:station])

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render json: @station, status: :created, location: @station }
      else
        format.html { render action: "new" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stations/1
  # PUT /stations/1.json
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end

  def add_device
    @station = Station.find(params[:id])
  end

end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>
      </div>
      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"название" %>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :"район" %>
      <%= f.text_field :name %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/_search.html.erb
<ul>
  <% @stations.each do |f| %>
      <li><%= link_to f.name, :action => 'show', :id => f.id %></li>
 <% end %>

</ul>

app/views/stations/add_device.html.erb
<h1>Добавить новые устройства</h1>

app/views/stations/edit.html.erb
<div class="alert alert-info ">
  <h1>Редактирование отделения</h1>
</div>
<%= render 'form' %>

<%= link_to 'Просмотр', @station %> |
<%= link_to 'Назад', stations_path %>

app/views/stations/index.html.erb
<div class="input-append">
<%= form_tag stations_path, :method => 'get' do %>

    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil, :class => "btn btn" %>
    </p>
<% end %>
  </div>


<div class="alert alert-info ">
  <h2>Список отделений</h2>
</div>
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Название</th>
    <th>Район</th>
    <th>Действия</th>
  </tr>
  </thead>
  <tbody>

  <% @stations.each do |station| %>

      <tr>
        <td><%= station.name %></td>
        <td><%= station.district_id %></td>


        <td class="ctrl"><%= link_to 'Просмотр', station %></td>
        <td class="ctrl"><%= link_to 'Удалить', station, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
      </tr>
      </tbody>
  <% end %>

  </table>

<br/>

<%= link_to 'Новое отделение', new_station_path, :class => "btn" %>

app/views/stations/new.html.erb
<div class="alert alert-info ">
<h2>Добавить новое отделение</h2>
 </div>
</br>

<%= render 'form' %>

<%= link_to 'Назад', stations_path %>

app/views/stations/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>
<div class="alert alert-info ">
  <h2>
    <b>Название:</b>
    <%= @station.name %>
  </h2>

  <h4>
    <b>Район:</b>
    <%= @station.district_id %>
  </h4>

</div>
<!-----------list of device---------->


</br>


<% if @modems.any? %>

    <div class="alert alert-success">
      <strong>МОДЕМЫ</strong>
    </div>

    <table class="table table-bordered">
      <thead>
      <tr class="success">
        <th>Тип</th>
        <th>Скорость</th>
        <th>Действия</th>
      </tr>
      </thead>
      <tbody>

      <% @modems.each do |modem| %>
          <% if modem.retirement? %>
              <tr class="error">

          <% else %>
              <tr>
          <% end %>
          <td><%= modem.modem_type %></td>
          <td> <%= modem.speed %> </td>

          <td class="ctrl"> <%= link_to "просмотр", station_modem_path(@station, modem) %></td>
          <td class="ctrl"><%= link_to "редактировать", edit_station_modem_path(@station, modem) %></td>

          </tr>
          </tbody>
      <% end %>
      </table>
<% end %>

<% if @printers.any? %>
    <div class="alert alert-success">
      <strong>ПЕЧАТНЫЕ УСТРОЙСТВА</strong>
    </div>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Устройство</th>
        <th>Тип</th>
        <th>Действия</th>

      </tr>
      </thead>
      <tbody>

      <% @printers.each do |pr| %>
          <% if pr.retirement? %>
              <tr class="error">

          <% else %>
              <tr>
          <% end %>

          <td><%= pr.device %></td>
          <td> <%= pr.printer_type %> </td>

          <td class="ctrl"> <%= link_to "просмотр", station_printer_path(@station, pr) %></td>
          <td class="ctrl"><%= link_to "редактировать", edit_station_printer_path(@station, pr) %></td>

          </tr>
          </tbody>
      <% end %>
      </table>
<% end %>

<% if @computers.any? %>
    <div class="alert alert-success">
      <strong>СВТ</strong>
    </div>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Компьютер</th>
        <th>Тип ЭВМ</th>
        <th>Действия</th>

      </tr>
      </thead>
      <tbody>

      <% @computers.each do |c| %>
          <% if c.retirement? %>
              <tr class="error">

          <% else %>
              <tr>
          <% end %>
          <td><%= c.platform %></td>
          <td> <%= c.comp_type %> </td>

          <td class="ctrl"> <%= link_to "просмотр", station_computer_path(@station, c) %></td>
          <td class="ctrl"><%= link_to "редактировать", edit_station_computer_path(@station, c) %></td>

          </tr>
          </tbody>
      <% end %>
      </table>
<% end %>

<% if @devices.any? %>
    <div class="alert alert-success">
      <strong>ДРУГОЕ ОБОРУДОВАНИЕ</strong>
    </div>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Тип</th>
        <th>Модель</th>
        <th>Действия</th>

      </tr>
      </thead>
      <tbody>

      <% @devices.each do |d| %>
          <% if d.retirement? %>
              <tr class="error">

          <% else %>
              <tr>

          <% end %>
          <td><%= d.device_type %></td>
          <td> <%= d.device_model %> </td>

          <td class="ctrl"> <%= link_to "просмотр", station_device_path(@station, d) %></td>
          <td class="ctrl"><%= link_to "редактировать", edit_station_device_path(@station, d) %></td>

          </tr>
          </tbody>
      <% end %>
      </table>
<% end %>
<p>
  <span class="badge badge-important"> </span> - закончен срок эксплуатации</p></br>

<!----------------------->

<%= link_to 'Добавить СВТ', new_station_computer_path(@station), :class => "btn" %>
<%= link_to 'Добавить другое оборудование', new_station_device_path(@station), :class => "btn" %>
<%= link_to 'Добавить ПУ', new_station_printer_path(@station), :class => "btn" %>
<%= link_to 'Добавить Модем', new_station_modem_path(@station) , :class => "btn"%>   </br>
<%= link_to 'Редактировать', edit_station_path(@station) %>|
<%= link_to 'Назад', stations_path %>