config/routes.rb
Practic::Application.routes.draw do

  get "static_pages/about"

  get 'admin' => 'admin/index'

  resources :users

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

  resources :stations do
    resources :devices
    resources :computers
    resources :printers
    resources :modems
  end

  post "user/create"
  get "user/:id" => "User#show"

  match 'about' => 'Static_Pages#about'

 root :to => 'stations#index'

end

app/models/computer.rb
class Computer < ActiveRecord::Base
  attr_accessible :comment, :commissioning, :comp_class,
                  :comp_type, :computer_model, :decommissioning,
                  :display, :hdd, :memory, :platform,
                  :processor, :source, :task, :station_id
  belongs_to :station

  def retirement?
    self.decommissioning < Date.today
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :comment, :commissioning, :decommissioning,
                  :device_model, :device_type, :source, :task , :station_id
  belongs_to :station


  def retirement?
           self.decommissioning  < Date.today
  end

end

app/models/modem.rb
class Modem < ActiveRecord::Base
  attr_accessible :comment, :commissioning, :decommissioning,
                  :model, :modem_type, :source, :speed, :task , :station_id
  belongs_to :station

  def retirement?
    self.decommissioning  < Date.today
  end
end

app/models/printer.rb
class Printer < ActiveRecord::Base
  attr_accessible :chroma, :comment, :commissioning,
                  :decommissioning, :device, :page_format,
                  :printer_model, :printer_type, :source, :task, :station_id
  belongs_to :station

  def retirement?
    self.decommissioning  < Date.today
  end
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :name

  has_many :computers, :dependent => :destroy
  has_many :devices, :dependent => :destroy
  has_many :modems, :dependent => :destroy
  has_many :printers, :dependent => :destroy
  validates :name, :presence => :true

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  #attr_accessor :name, :password_digest
  attr_accessible :name, :password, :password_confirmation

  validates :name, :presence => :true, :uniqueness => :true
  has_secure_password
  after_destroy :ensure_an_admin_remains

  private

  def ensure_an_admin_remains
    if User.count.zero?
     # raise "Последний пользователь не может быть удален"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  ## GET /users/1
  ## GET /users/1.json
  #def show
  #  @user = User.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @user }
  #  end
  #end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path,
                                  notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path,
                                  notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
   begin
      @user.destroy
    flash[:notice] = "User #{@user.name} has been deleted"
    rescue Exception => e
     flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/modems_helper.rb
module ModemsHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
<p><%= Time.now %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designed and coded by <a href="mailto:pavlovskes@gmail.com">Evgeny Pavlovsky</a>, Starovoitov Sergei.
    <nav>
      © 2013
    </nav>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class=" navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>

        <ul class="nav pull-right">


          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>

          <% if session[:user_id] %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Show <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Stations List", stations_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                </ul>
              </li>

               <li><%= link_to 'Logout', logout_path, method: :delete %>          </li>

          <% else %>
              <li><%= link_to 'Sign in', login_url %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>Practic</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>


<div class="container">

  <!--------------------------->

  <section class="round">
    <% flash.each do |key, value| %>
        <div class="flash <%= key %> ">
          <%= value %>
        </div>
    <% end %>

  </section>

  <!---------------------------------------------->
  <div class="center hero-unit">

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</header>


</html>

app/views/shared/_error_messages.html.erb
<% if @division.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <%= pluralize(@division.errors.count, "error") %>
        prohibited this user from being saved:
      </div>

      <p>There were problems with the following fields:</p>
      <ul>
        <% @division.errors.full_messages.each do |msg| %>
            <li>*<%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/about.html.erb
<!doctype html>		
<html>
	<head>
		<meta charset = "utf-8" />
		<link rel="stylesheet" href="style.css">
		<title>about</title>
	</head>
	<body>
		<p>
			<pre>
				Программное средство АРМ «Учет СВТ» предназначено для ведения статистического учета 
				компьютерной техники и периферийных устройств в МЧС Республики Беларусь. 
			</pre>
		</p>
		<p>
			<pre>
				Данные имеют древовидную структуру:
			</pre>
		</p>
		<img src="db.png" alt = "database diagram(no details)">	
		<p>
			<pre>
				На странице отделения можно просмотреть все принадлежащее ему оборудование.
				Если отделение будет удалено, то вместе с ним удалится и оборудование.

				Можно перейти на страницу каждого СВТ или Периферийного устройства для просмотра всех данных.
				СВТ и ПУ срок эксплуатации которых закончился будут выделены красным цветом.

				При создании отделений и оборудования проводится валидация данных:
			</pre>
		</p>
		<img src="error.png" alt = "validation error">
	</body>
</html>